### ISSUE TITLE
catkin_make error regarding pcl

### ISSUE THREAD

**Issue by kishorekumar29** [MalcolmMielle/ros_open_tld_3d#1]
As you advised in ros_open_tld version, I tried compiling ros_open_tld_3d in my workspace using "catkin_make" but it failed with following error.

CMake Error at /opt/ros/indigo/share/catkin/cmake/catkinConfig.cmake:75 (find_package):
  Could not find a package configuration file provided by "pcl" with any of
  the following names:

```
pclConfig.cmake
pcl-config.cmake
```

  Add the installation prefix of "pcl" to CMAKE_PREFIX_PATH or set "pcl_DIR"
  to a directory containing one of the above files.  If "pcl" provides a
  separate development package or SDK, be sure it has been installed.
Call Stack (most recent call first):
  ros_open_tld_3d/CMakeLists.txt:7 (find_package)

-- Configuring incomplete, errors occurred!
See also "/home/robotics/ros_opencv/build/CMakeFiles/CMakeOutput.log".
See also "/home/robotics/ros_opencv/build/CMakeFiles/CMakeError.log".
make: **\* [cmake_check_build_system] Error 1

After some research i came to know this issue is because of pcl libraries and we need to take some extra care to compile pcl libraries in ROS, please guide towards the changes need to be done.
I am using ROS indigo, ubuntu 14.04, latest version of ros pcl package is installed.

**Comment by MalcolmMielle** [comment]
[On this issue you opened](https://github.com/MalcolmMielle/ros_open_tld/issues/1), I said you should use this package if you don't mind the PCL dependency only. There would be quite a few changes to do to remove the PCL dependencies.

Do you have any particular reason not to install PCL ? If not you should just install it with `sudo apt-get install pcl-devel` or `sudo apt-get install pcl` or something similar.

If you don't want to install PCL please **do not use this package** but [this one](https://github.com/MalcolmMielle/ros_open_tld).

PS : also, could you only post to github and not on both github and ROS Answer ?

**Comment by kishorekumar29** [comment]
"ros-indigo-pcl-ros" was already installed but still the issue persists, i tried to install the packages you suggested above but i got "unable to locate the package". Please guide me through the exact package name to be installed. I absolutely have no problem in installing pcl.
